# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10cb6f6f93ffa172fd9555bae39c9eb342ebdf087321ad51da842d23241a5be4d2eb78d21d23a119a1c325397448059a0dd616d2034d7a0cbe864096b8820367

test:
  secret_key_base: a63709c8e58768931c40961819a016ebb8bc4048bc69d5dc49432af035a7a721f6e6a282fae1966be3be3b22e9aadc14dea5e9d7c8bb4e047fca3de1694adb80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
